In [16]:
import os
import sys
module_path = os.path.abspath(os.path.join('..'))
if module_path not in sys.path:
    sys.path.append(module_path)

import pandas as pd
from src.analysis.performance_calculator import PerformanceCalculator

pc = PerformanceCalculator()

In [17]:
def test_calculate_group_returns():
    test_data = [
        # 第一天数据
        {'date': '2023-01-01', 'instrument': 'A', 'group': '0', 'daily_ret': 0.012},
        {'date': '2023-01-01', 'instrument': 'B', 'group': '1', 'daily_ret': 0.023},
        {'date': '2023-01-01', 'instrument': 'C', 'group': '2', 'daily_ret': 0.035},
        
        # 第二天数据
        {'date': '2023-01-02', 'instrument': 'A', 'group': '0', 'daily_ret': -0.005},
        {'date': '2023-01-02', 'instrument': 'B', 'group': '1', 'daily_ret': 0.010},
        {'date': '2023-01-02', 'instrument': 'C', 'group': '2', 'daily_ret': 0.028},
        
        # 第三天数据
        {'date': '2023-01-03', 'instrument': 'A', 'group': '0', 'daily_ret': 0.008},
        {'date': '2023-01-03', 'instrument': 'B', 'group': '1', 'daily_ret': 0.015},
        {'date': '2023-01-03', 'instrument': 'C', 'group': '2', 'daily_ret': 0.020}
    ]

    test_df = pd.DataFrame(test_data)
    result_df = pc.calculate_group_returns(test_df)
    display(test_df, result_df)

test_calculate_group_returns()

         date instrument group  daily_ret
0  2023-01-01          A     0      0.012
1  2023-01-01          B     1      0.023
2  2023-01-01          C     2      0.035
3  2023-01-02          A     0     -0.005
4  2023-01-02          B     1      0.010
5  2023-01-02          C     2      0.028
6  2023-01-03          A     0      0.008
7  2023-01-03          B     1      0.015
8  2023-01-03          C     2      0.020

group        date      0      1      2     ls
0      2023-01-01  0.012  0.023  0.035  0.023
1      2023-01-02 -0.005  0.010  0.028  0.033
2      2023-01-03  0.008  0.015  0.020  0.012

In [18]:
def test_calculate_cumulative_returns():
    test_df = pd.DataFrame({
        'date': ['2023-01-01', '2023-01-02', '2023-01-03'],
        '0': [0.012, -0.005, 0.008],
        '1': [0.023, 0.010, 0.015],
        '2': [0.035, 0.028, 0.020],
        'ls': [0.023, 0.033, 0.012]
    })

    test_df_bm = pd.DataFrame({
        'date': ['2023-01-01', '2023-01-02', '2023-01-03'],
        'instrument': ['A', 'A', 'A'],
        'benchmark_ret': [0.002, 0.03, 0.02]
    })

    result_df = pc.calculate_cumulative_returns(test_df, test_df_bm)
    display(test_df, result_df)

test_calculate_cumulative_returns()

         date      0      1      2     ls
0  2023-01-01  0.012  0.023  0.035  0.023
1  2023-01-02 -0.005  0.010  0.028  0.033
2  2023-01-03  0.008  0.015  0.020  0.012

         date      0      1      2     ls     bm
0  2023-01-01  0.012  0.023  0.035  0.023  0.002
1  2023-01-02  0.007  0.033  0.063  0.056  0.032
2  2023-01-03  0.015  0.048  0.083  0.068  0.052

In [19]:
def test__calculate_performance_metrics_by_series():
    dates = pd.date_range('2023-01-01', periods=5)
    test_series_returns = pd.Series([0.01, 0.02, -0.01, 0.03, 0.005], index=dates)
    test_series_benchmark = pd.Series([0.008, 0.015, -0.008, 0.025, 0.003], index=dates)
    
    metrics = pc._calculate_performance_metrics_by_series(test_series_returns, test_series_benchmark)
    display(metrics)

test__calculate_performance_metrics_by_series()

{'return_ratio': np.float64(0.055),
 'annual_return_ratio': np.float64(2.662),
 'ex_return_ratio': np.float64(0.012),
 'ex_annual_return_ratio': np.float64(0.5808),
 'sharp_ratio': np.float64(11.3627),
 'return_volatility': np.float64(0.2407),
 'information_ratio': np.float64(0.7253),
 'max_drawdown': np.float64(-0.01),
 'win_percent': np.float64(0.8),
 'trading_days': 5,
 'ret_3': np.float64(0.025),
 'ret_10': np.float64(nan),
 'ret_21': np.float64(nan),
 'ret_63': np.float64(nan),
 'ret_126': np.float64(nan),
 'ret_252': np.float64(nan)}

In [20]:
def test_calculate_performance_metrics():
    test_df = pd.DataFrame({
        'date': ['2023-01-01', '2023-01-02', '2023-01-03'],
        '0': [0.012, -0.005, 0.008],
        '1': [0.023, 0.010, 0.015],
        '2': [0.035, 0.028, 0.020],
        'ls': [0.023, 0.033, 0.012]
    })
    test_df_bm = pd.DataFrame({
        'date': ['2023-01-01', '2023-01-02', '2023-01-03'],
        'instrument': ['A', 'A', 'A'],
        'benchmark_ret': [0.002, 0.03, 0.02]
    })

    display(pc.calculate_performance_metrics(test_df,test_df_bm,"long"))

test_calculate_performance_metrics()

{'return_ratio': np.float64(0.083),
 'annual_return_ratio': np.float64(6.6953),
 'ex_return_ratio': np.float64(0.031),
 'ex_annual_return_ratio': np.float64(2.5007),
 'sharp_ratio': np.float64(58.2101),
 'return_volatility': np.float64(0.1191),
 'information_ratio': np.float64(3.6862),
 'max_drawdown': np.float64(0.0),
 'win_percent': np.float64(1.0),
 'trading_days': 3,
 'ret_3': np.float64(0.083),
 'ret_10': np.float64(nan),
 'ret_21': np.float64(nan),
 'ret_63': np.float64(nan),
 'ret_126': np.float64(nan),
 'ret_252': np.float64(nan)}

In [21]:
def test_calculate_daily_ic():
    test_data = [
        # 第一天数据
        {'date': '2023-01-01', 'factor': -0.23, 'group': '0', 'daily_ret': 0.012},
        {'date': '2023-01-01', 'factor': 0.85, 'group': '1', 'daily_ret': 0.023},
        {'date': '2023-01-01', 'factor': 1.23, 'group': '2', 'daily_ret': 0.035},
        
        # 第二天数据
        {'date': '2023-01-02', 'factor': -0.05, 'group': '0', 'daily_ret': -0.005},
        {'date': '2023-01-02', 'factor': -0.06, 'group': '1', 'daily_ret': 0.010},
        {'date': '2023-01-02', 'factor': 0.15, 'group': '2', 'daily_ret': 0.028},
        
        # 第三天数据
        {'date': '2023-01-03', 'factor': 0.02, 'group': '0', 'daily_ret': 0.008},
        {'date': '2023-01-03', 'factor': 0.23, 'group': '1', 'daily_ret': 0.015},
        {'date': '2023-01-03', 'factor': 0.85, 'group': '2', 'daily_ret': 0.020}
    ]

    test_df = pd.DataFrame(test_data)
    result_df = pc.calculate_daily_ic(test_df)

    display(test_df, result_df)

test_calculate_daily_ic()

         date  factor group  daily_ret
0  2023-01-01   -0.23     0      0.012
1  2023-01-01    0.85     1      0.023
2  2023-01-01    1.23     2      0.035
3  2023-01-02   -0.05     0     -0.005
4  2023-01-02   -0.06     1      0.010
5  2023-01-02    0.15     2      0.028
6  2023-01-03    0.02     0      0.008
7  2023-01-03    0.23     1      0.015
8  2023-01-03    0.85     2      0.020

            g_ic  ic_cumsum  ic_roll_ma
date
2023-01-01   1.0        1.0         NaN
2023-01-02   0.5        1.5         NaN
2023-01-03   1.0        2.5         NaN

In [22]:
def test_calculate_portfolio_ic_metrics():
    test_data = [
        # 第一天数据
        {'date': '2023-01-01', 'factor': -0.23, 'group': '0', 'daily_ret': 0.012},
        {'date': '2023-01-01', 'factor': 0.85, 'group': '1', 'daily_ret': 0.023},
        {'date': '2023-01-01', 'factor': 1.23, 'group': '2', 'daily_ret': 0.035},
        {'date': '2023-01-01', 'factor': -0.33, 'group': '0', 'daily_ret': 0.002},
        {'date': '2023-01-01', 'factor': 0.45, 'group': '1', 'daily_ret': 0.063},
        {'date': '2023-01-01', 'factor': 0.43, 'group': '2', 'daily_ret': 0.015},
        
        # 第二天数据
        {'date': '2023-01-02', 'factor': -0.05, 'group': '0', 'daily_ret': -0.005},
        {'date': '2023-01-02', 'factor': -0.06, 'group': '1', 'daily_ret': 0.010},
        {'date': '2023-01-02', 'factor': 0.15, 'group': '2', 'daily_ret': 0.028},
        {'date': '2023-01-02', 'factor': 0.23, 'group': '0', 'daily_ret': -0.015},
        {'date': '2023-01-02', 'factor': -0.52, 'group': '1', 'daily_ret': 0.003},
        {'date': '2023-01-02', 'factor': 0.33, 'group': '2', 'daily_ret': 0.033},
        
        # 第三天数据
        {'date': '2023-01-03', 'factor': 0.02, 'group': '0', 'daily_ret': 0.008},
        {'date': '2023-01-03', 'factor': 0.23, 'group': '1', 'daily_ret': 0.015},
        {'date': '2023-01-03', 'factor': 0.85, 'group': '2', 'daily_ret': 0.020},
        {'date': '2023-01-03', 'factor': 0.01, 'group': '0', 'daily_ret': 0.102},
        {'date': '2023-01-03', 'factor': 0.22, 'group': '1', 'daily_ret': 0.026},
        {'date': '2023-01-03', 'factor': 0.99, 'group': '2', 'daily_ret': 0.011},
    ]

    test_df = pd.DataFrame(test_data)
    result_df = pc.calculate_portfolio_ic_metrics(test_df, portfolio_type="long")

    display(test_df, result_df)

test_calculate_portfolio_ic_metrics()

          date  factor group  daily_ret
0   2023-01-01   -0.23     0      0.012
1   2023-01-01    0.85     1      0.023
2   2023-01-01    1.23     2      0.035
3   2023-01-01   -0.33     0      0.002
4   2023-01-01    0.45     1      0.063
5   2023-01-01    0.43     2      0.015
6   2023-01-02   -0.05     0     -0.005
7   2023-01-02   -0.06     1      0.010
8   2023-01-02    0.15     2      0.028
9   2023-01-02    0.23     0     -0.015
10  2023-01-02   -0.52     1      0.003
11  2023-01-02    0.33     2      0.033
12  2023-01-03    0.02     0      0.008
13  2023-01-03    0.23     1      0.015
14  2023-01-03    0.85     2      0.020
15  2023-01-03    0.01     0      0.102
16  2023-01-03    0.22     1      0.026
17  2023-01-03    0.99     2      0.011

{'ic': np.float64(0.3333),
 'icir': np.float64(0.3536),
 'ic_3': np.float64(0.3333),
 'ic_10': np.float64(nan),
 'ic_21': np.float64(nan),
 'ic_63': np.float64(nan),
 'ic_126': np.float64(nan),
 'ic_252': np.float64(nan)}

In [23]:
def test_calculate_turnover_metrics():
    test_df = pd.DataFrame({
        'date': [
            '2023-01-01', '2023-01-01', '2023-01-01', 
            '2023-01-01', '2023-01-01', '2023-01-01',
            '2023-01-02', '2023-01-02', '2023-01-02'
        ],
        'group': [
            '0', '1', '2', 
            '0', '1', '2',
            '0', '1', '2'
        ],
        'instrument': [
            'A', 'C', 'E',
            'B', 'D', 'F',
            'B', 'D', 'F'
        ]
    })
    result_df = pc.calculate_turnover_metrics(test_df, 'long_short')
    display(test_df, result_df)

test_calculate_turnover_metrics()

         date group instrument
0  2023-01-01     0          A
1  2023-01-01     1          C
2  2023-01-01     2          E
3  2023-01-01     0          B
4  2023-01-01     1          D
5  2023-01-01     2          F
6  2023-01-02     0          B
7  2023-01-02     1          D
8  2023-01-02     2          F

{'turnover': np.float64(0.5)}

In [24]:
def test__calculate_yearly_performance_by_series():
    dates = pd.date_range('2023-01-01', periods=5)
    test_series_returns = pd.Series([0.01, 0.02, -0.01, 0.03, 0.005], index=dates)
    test_series_benchmark = pd.Series([0.008, 0.015, -0.008, 0.025, 0.003], index=dates)
    
    metrics = pc._calculate_yearly_performance_by_series(test_series_returns, test_series_benchmark)
    display(metrics)

test__calculate_yearly_performance_by_series()

,return_ratio,annual_return_ratio,ex_return_ratio,ex_annual_return_ratio,sharp_ratio,return_volatility,information_ratio,max_drawdown,win_percent,trading_days
year,,,,,,,,,,
2023,0.055,2.662,0.012,0.5808,11.3627,0.2407,0.7253,-0.01,0.8,5

In [25]:
def test_calculate_yearly_performance():
    test_df = pd.DataFrame({
        'date': ['2023-01-01', '2023-01-02', '2023-01-03'],
        '0': [0.012, -0.005, 0.008],
        '1': [0.023, 0.010, 0.015],
        '2': [0.035, 0.028, 0.020],
        'ls': [0.023, 0.033, 0.012]
    })
    test_df_bm = pd.DataFrame({
        'date': ['2023-01-01', '2023-01-02', '2023-01-03'],
        'instrument': ['A', 'A', 'A'],
        'benchmark_ret': [0.002, 0.03, 0.02]
    })

    test_df['date'] = pd.to_datetime(test_df['date']) 
    test_df_bm['date'] = pd.to_datetime(test_df_bm['date']) 
    display(pc.calculate_yearly_performance(test_df,test_df_bm,"long"))

test_calculate_yearly_performance()

,return_ratio,annual_return_ratio,ex_return_ratio,ex_annual_return_ratio,sharp_ratio,return_volatility,information_ratio,max_drawdown,win_percent,trading_days
year,,,,,,,,,,
2023,0.083,6.6953,0.031,2.5007,58.2101,0.1191,3.6862,0.0,1.0,3

In [26]:
def test_calculate_yearly_ic():
    test_data = [
        # 第一天数据
        {'date': '2023-01-01', 'factor': -0.23, 'group': '0', 'daily_ret': 0.012},
        {'date': '2023-01-01', 'factor': 0.85, 'group': '1', 'daily_ret': 0.023},
        {'date': '2023-01-01', 'factor': 1.23, 'group': '2', 'daily_ret': 0.035},
        {'date': '2023-01-01', 'factor': -0.33, 'group': '0', 'daily_ret': 0.002},
        {'date': '2023-01-01', 'factor': 0.45, 'group': '1', 'daily_ret': 0.063},
        {'date': '2023-01-01', 'factor': 0.43, 'group': '2', 'daily_ret': 0.015},
        
        # 第二天数据
        {'date': '2024-01-02', 'factor': -0.05, 'group': '0', 'daily_ret': -0.005},
        {'date': '2024-01-02', 'factor': -0.06, 'group': '1', 'daily_ret': 0.010},
        {'date': '2024-01-02', 'factor': 0.15, 'group': '2', 'daily_ret': 0.028},
        {'date': '2024-01-02', 'factor': 0.23, 'group': '0', 'daily_ret': -0.015},
        {'date': '2024-01-02', 'factor': -0.52, 'group': '1', 'daily_ret': 0.003},
        {'date': '2024-01-02', 'factor': 0.33, 'group': '2', 'daily_ret': 0.033},
        
        # 第三天数据
        {'date': '2025-01-03', 'factor': 0.02, 'group': '0', 'daily_ret': 0.008},
        {'date': '2025-01-03', 'factor': 0.23, 'group': '1', 'daily_ret': 0.015},
        {'date': '2025-01-03', 'factor': 0.85, 'group': '2', 'daily_ret': 0.020},
        {'date': '2025-01-03', 'factor': 0.01, 'group': '0', 'daily_ret': 0.102},
        {'date': '2025-01-03', 'factor': 0.22, 'group': '1', 'daily_ret': 0.026},
        {'date': '2025-01-03', 'factor': 0.99, 'group': '2', 'daily_ret': 0.011},
    ]

    test_df = pd.DataFrame(test_data)
    test_df["date"] = pd.to_datetime(test_df["date"])
    result_df = pc.calculate_yearly_ic(test_df)

    display(test_df, result_df)
    

test_calculate_yearly_ic()

         date  factor group  daily_ret
0  2023-01-01   -0.23     0      0.012
1  2023-01-01    0.85     1      0.023
2  2023-01-01    1.23     2      0.035
3  2023-01-01   -0.33     0      0.002
4  2023-01-01    0.45     1      0.063
5  2023-01-01    0.43     2      0.015
6  2024-01-02   -0.05     0     -0.005
7  2024-01-02   -0.06     1      0.010
8  2024-01-02    0.15     2      0.028
9  2024-01-02    0.23     0     -0.015
10 2024-01-02   -0.52     1      0.003
11 2024-01-02    0.33     2      0.033
12 2025-01-03    0.02     0      0.008
13 2025-01-03    0.23     1      0.015
14 2025-01-03    0.85     2      0.020
15 2025-01-03    0.01     0      0.102
16 2025-01-03    0.22     1      0.026
17 2025-01-03    0.99     2      0.011

year
2023    1.0
2024    1.0
2025   -1.0
dtype: float64